const ClassMenu = [
    //Chest Exercise.
    { 
        id : 1,
        image : "https://i.pinimg.com/564x/c6/4e/a9/c64ea9a4aeec242e709e0ee4f0e06c2e.jpg",
        youtube:"https://www.youtube.com/watch?v=mpT7PAFeA68",
        name : 'barbell bench press',
        category : 'Chest',
        description : "The barbell bench press is a compound exercise that works the upper chest muscles",
    },
    {
        id : 2,
        image : "https://i.pinimg.com/236x/cb/42/58/cb4258cc6b63f56f7424fdffbb2c9488.jpg",
        youtube:"https://www.youtube.com/shorts/_ozQOVLyVVE",
        name : "incline barbell bench press",
        category : 'Chest',
        //time : ,
        description : "The incline barbell bench press is a compound exercise that works the middle chest muscles",
    },
    {
        id : 3,
        image : "https://i.pinimg.com/564x/22/16/d2/2216d22fe0a913ad49a836c41ae80671.jpg",
        youtube:"https://www.youtube.com/shorts/tFgn4pBSr6Y",
        name : "decline barbell bench press",
        category : 'Chest',
        //time : ,
        description : "The decline barbell bench press is a compound exercise that works the lower chest muscles",
    },
    {
        id : 4,
        image : "https://i.pinimg.com/564x/0c/18/3b/0c183bfa4885ab92658c812e2a93e690.jpg",
        youtube:"https://www.youtube.com/shorts/_8mLd6uZhYU",
        name : "Incline bench dumbbell fly",
        category : 'Chest',
        //time : ,
        description : "The incline dumbbell fly is a chest exercise that targets the upper chest, shoulders, and triceps",
    },
    {
        id : 5,
        image : "https://i.pinimg.com/564x/3f/18/96/3f1896a95a08a5fa79f503f15eea0194.jpg",
        youtube:"https://www.youtube.com/shorts/c2tv4pMhf3w",
        name : "dumbbell bench press",
        category : 'Chest',
        //time : ,
        description : "The dumbbell bench press is a popular exercise that builds muscle in your upper body, especially your chest.",
    },
    {
        id : 6,
        image : "https://i.pinimg.com/564x/ed/4d/1f/ed4d1f6ce1bdbb4cda128ac708272500.jpg",
        youtube:"https://www.youtube.com/shorts/z_yY1o8i6U0",
        name : "butterfly",
        category : 'Chest',
        //time : ,
        description : "The dumbbell fly is an effective way to build the chest and challenge the pectoral muscles.",
    },
    {
        id : 7,
        image : "https://i.pinimg.com/564x/04/6c/60/046c604edda8f24946d9d6ba17f9417d.jpg",
        youtube:"https://www.youtube.com/shorts/NK2wMQpsJs0",
        name : " Cable Standing Fly",
        category : 'Chest',
        //time : ,
        description : "Standing flyes exercise and build strength in several of the major muscle groups of the upper body Strong chest muscles.",
    },
    {
        id : 8,
        image : "https://i.pinimg.com/564x/25/af/7f/25af7fdf88b91a9c0e8d1cdde531010a.jpg",
        youtube: "https://www.youtube.com/shorts/ztGq6C7a3rI",
        name : " meachine press",
        category : 'Chest',
        //time : ,
        description : "This exercise targets the pectorals, the main muscles of the chest.",
},
{
    id : 9,
    image : "https://i.pinimg.com/564x/f5/75/f9/f575f904070f10636f8e146d941e7e94.jpg",
    youtube:"https://www.youtube.com/shorts/i5eHTans_v0",
    name : " dummbell fullover",
    category : 'Chest',
    //time : ,
    description : "The pectoralis major, which spans from your sternum to your collarbone and upper arms, is the main muscle that moves the weight.",
},
{
    id : 10,
    image : "https://i.pinimg.com/736x/6c/63/86/6c6386e0a8755936f5441bf1cdfa6235.jpg",
    youtube: "https://www.youtube.com/shorts/8N0vhjOfQ6Y",
    name : "push chest",
    category : 'Chest',
    //time : ,
    description : "Push-ups are a great exercise for building strength and definition in your chest muscles.",
},


//Back Excercise.
{
    id : 11,
    image : "https://i.pinimg.com/236x/d9/bd/f0/d9bdf01651417ee1639e74b599d1e3e2.jpg",
    youtube: "https://www.youtube.com/shorts/Y6I1mOmBOzE",
    name : "Chin Ups",
    category : 'Back',
    //time : ,
    description : "Chin-ups are a resistance exercise that can help you build strength and definition in your upper body, and improve your grip strength and posture.",
},
{
    id : 12,
    image : "https://i.pinimg.com/originals/5d/e2/ec/5de2ec305b894aa6ffcd56cc1a545979.jpg",
    youtube: "https://www.youtube.com/shorts/xkRjDHsUmiI",
    name : "Lat Pulldowns",
    category : 'Back',
    //time : ,
    description : "Lat pulldowns are a great exercise that can help you build upper body strength and improve your posture.",
},
{
    id : 13,
    image : "https://i.pinimg.com/originals/fd/be/e5/fdbee5d6944431082ef6566b6dd8077f.png",
    youtube: "https://www.youtube.com/shorts/vzEF3r9O3rg",
    name : "Reverse Grip Lat Pulldowns",
    category : 'Back',
    //time : ,
    description : "Are Reverse Grip Lat Pulldowns Good? Reverse grip lat pulldowns are good for building back and bicep strength.",
},
{
    id : 14,
    image : "https://i.pinimg.com/originals/00/c4/a4/00c4a4467c97e7885368e93e89301e3b.png",
    youtube:"https://www.youtube.com/watch?v=IjoFCmLX7z0",
    name : "Close Grip Lat Pulldowns",
    category : 'Back',
    //time : ,
    description : "The close-grip lat pulldown is a back exercise that can help improve posture, build strength, and protect your shoulders.",
},
{
    id : 15,
    image : "https://i.pinimg.com/originals/91/80/e5/9180e54186d706a494fea2e21712ac2a.jpg",
    youtube:"https://www.youtube.com/shorts/oOftkcyny4c",
    name : "Bend over barbell Rows",
    category : 'Back',
    //time : ,
    description : "Additionally, understanding the barbell row benefits, such as targeting the mid and upper back muscles and avoiding common mistakes, can further enhance posture improvement.",
},
{
    id : 16,
    image : "https://i.pinimg.com/236x/f9/46/e8/f946e870d3d2a86d886810ec81dd142c.jpg",
    youtube:"https://www.youtube.com/shorts/kxayYbYmM-A",
    name : "Single Arm Dumbell Row",
    category : 'Back',
    //time : ,
    description : "Single arm rows work the back muscles, namely the lats, trapezius, rhomboids, and rear deltoids, with the core and biceps also engaged.",
},
{
    id : 17,
    image : "https://i.pinimg.com/originals/fa/34/22/fa342278cdd5cfb6f04214902f535f9c.jpg",
    youtube:"https://www.youtube.com/shorts/NPPHXK7F_fI",
    name : "Cable seated Row ",
    category : 'Back',
    //time : ,
    description : "Seated cable rows increase upper-body strength by activating multiple muscle groups throughout the body, including back muscles like the latissimus dorsi in your middle back, the erector spinea muscles, the rhomboids in your upper back, and the lower trapezius.",
},
{
    id : 18,
    image : " https://i.pinimg.com/236x/2b/81/be/2b81bebcdb20e214f1d93375ca695e6a.jpg",
    youtube:"https://www.youtube.com/shorts/xmoQUz1RLLI",
    name : "Rope Straight Arm Pull Down",
    category : 'Back',
    //time : ,
    description : "It both stretches and contracts the muscles of the lats (latissimus dorsi) as well as providing additional activation to the other upper back muscles and the core.",
},
{
    id : 19,
    image : "https://i.pinimg.com/236x/eb/b8/01/ebb801502275ff9f27e01e1aed93e307.jpg",
    youtube:"https://www.youtube.com/shorts/aomPYWYu1co",
    name : "Lever Seated Row",
    category : 'Back',
    //time : ,
    description : "This exercise is commonly used to strengthen the upper back and improve posture.",
},
{
    id : 20,
    image : "https://i.pinimg.com/564x/f5/75/f9/f575f904070f10636f8e146d941e7e94.jpg",
    youtube:"https://www.youtube.com/shorts/i5eHTans_v0",
    name : " dummbell fullover",
    category : 'Back',
    //time : ,
    description : "The pectoralis major, which spans from your sternum to your collarbone and upper arms, is the main muscle that moves the weight.",
},

//Bicep Exercise.
{
    id : 21,
    image : "https://i.pinimg.com/564x/16/79/58/16795832a8cb1eb9669d12bab82581d6.jpg",
    youtube:"https://www.youtube.com/shorts/PqynIjXd-YA",
    name : "Barbell Drag Curl",
    category : 'Bicep',
    //time : ,
    description : "Barbell drag curls are a bicep exercise that can help you build strength and size in your biceps.",
},
{
    id : 22,
    image : "https://i.pinimg.com/564x/39/77/5f/39775fc759c770acd49aa1cb2c4b8f3d.jpg",
    youtube:"https://www.youtube.com/shorts/JtTxAVvDjeQ",
    name : "Bicep curl",
    category : 'Bicep',
    //time : ,
    description : "Consistently performing the bicep curl will help you build strength in the upper arm and learn to use your arm muscles correctly, bracing with your core muscles.",
},
{
    id : 23,
    image : "https://i.pinimg.com/236x/d6/17/85/d617850c924261366337453bbf1b7222.jpg",
    youtube:"https://www.youtube.com/shorts/X9ZKsxdLDYk",
    name : "Seated Alternating Dumbbell Curl",
    category : 'Bicep',
    //time : ,
    description : "This exercise is a great way to build strength and size in your biceps.",
},
{
    id : 24,
    image : "https://i.pinimg.com/564x/81/f0/85/81f0855f419d378af8689e8052d1600d.jpg",
    youtube:"https://www.youtube.com/shorts/oFhpIbtq6-c",
    name : "Hammer Curl",
    category : 'Bicep',
    //time : ,
    description : "They're beneficial to add mass to your arms and can help focus more attention on the short head of the biceps. They may be easier to tolerate than the traditional biceps curl.",
},
{
    id : 25,
    image : "https://i.pinimg.com/564x/e4/d4/c6/e4d4c661b02fcb55efa33d3c2dbb6d4b.jpg",
    youtube:"https://www.youtube.com/shorts/KE2YOKUpzHg",
    name : "Ez Bar Preacher Url",
    category : 'Bicep',
    //time : ,
    description : "The EZ bar preacher curl targets the biceps more effectively by isolating them and reducing shoulder involvement. It also helps improve arm strength and size while minimizing strain on the wrists.",
},
{
    id : 26,
    image : "https://i.pinimg.com/236x/28/0b/4b/280b4bf9c8d8b9e8d4701d357b5cdb30.jpg",
    youtube:"https://www.youtube.com/shorts/X0otkmaQ7G4",
    name : " Preacher Url",
    category : 'Bicep',
    //time : ,
    description : "Preacher curls are an effective exercise to build strength, power, and definition in the biceps and forearm muscles.",
},
{
    id : 27,
    image : "https://i.pinimg.com/736x/c3/32/63/c33263e1a4a3fc85e58cd3c3c050a01c.jpg",
    youtube:"https://www.youtube.com/shorts/Tr6ZHq2OQmk",
    name : "Curl Con Cable",
    category : 'Bicep',
    //time : ,
    description : "The biceps brachii is forced to work against the resistance that the cable machine is providing as well as an increased ground reaction force, and so this exercise is effective for promoting muscle growth and improved strength in the biceps.",
},
{
    id : 28,
    image : "https://i.pinimg.com/564x/84/f3/3a/84f33ab1770f1444a727621c37017499.jpg",
    youtube:"https://www.youtube.com/shorts/Cyy203PY3b8",
    name : "Dummbell Conentration Curl",
    category : 'Bicep',
    //time : ,
    description : "he dumbbell concentration curl focuses on isolating the biceps for improved muscle definition and peak. It also enhances muscle contraction and control, promoting better bicep strength and size.",
},

//Triceps Exercise.
{
    id : 29,
    image : "https://i.pinimg.com/736x/90/0f/94/900f9464ed98c7b161f66f196d3b5313.jpg",
    youtube:"https://www.youtube.com/shorts/LGWZRL5GzwE",
    name : "Close Grip Barbell Press",
    category : 'Tricep',
    //time : ,
    description : "The Close Grip Barbell Press strengthens your triceps and improves arm definition. It also enhances overall upper body strength.",
},
{
    id : 30,
    image : "https://i.pinimg.com/474x/1b/d2/92/1bd2926ba40ee6b9265ccec2d125b2ec.jpg",
    youtube:"https://www.youtube.com/shorts/t0DYFknBqHE",
    name : "Bar Skull Crushers",
    category : 'Tricep',
    //time : ,
    description : "Bar Skull Crushers target your triceps and boost arm strength. They also improve upper body muscle tone.",
},
{
    id : 31,
    image : "https://i.pinimg.com/236x/92/d8/0f/92d80f9a85f380385457cf198331057e.jpg",
    youtube:"https://www.youtube.com/shorts/KIUsudC0wQI",
    name : "Dumbbell One Arm Tricep",
    category : 'Tricep',
    //time : ,
    description : "The Dumbbell One-Arm Tricep Extension builds triceps strength and definition. It also helps improve arm stability and control.",
},
{
    id : 32,
    image : "https://i.pinimg.com/originals/13/f5/aa/13f5aa4ef69503a77e67cf6390eb6281.jpg",
    youtube:"https://www.youtube.com/shorts/8FNGBJUHfsA",
    name : "Dumbbell Overhead",
    category : 'Tricep',
    //time : ,
    description : "Dumbbell overhead presses can increase your core strength and stability.",
},
{
    id : 33,
    image : "https://i.pinimg.com/236x/2f/94/9a/2f949ab8cdf82ad1b075722b57f43b95.jpg",
    youtube:"https://www.youtube.com/shorts/rS_8yEfIHqo",
    name : "Rope Overheadhead Extension",
    category : 'Tricep',
    //time : ,
    description : "The rope overhead tricep extension is an exercise that isolates and strengthens the triceps, particularly the long head, while also improving shoulder stability.",
},
{
    id : 34,
    image : "https://i.pinimg.com/236x/b0/29/04/b02904060fa91ca7faba8705b8c4cd8c.jpg",
    youtube:"https://www.youtube.com/shorts/rHvDqkzNIqg",
    name : "Rope Pushdown",
    category : 'Tricep',
    //time : ,
    description : "A rope-pulling exercise will target the back, biceps, forearms, core muscles, and cardiovascular system.",
},
{
    id : 35,
        image : "https://i.pinimg.com/originals/9e/fb/79/9efb793170c6625f030f64be63c2df9c.jpg",
        youtube:"https://www.youtube.com/shorts/h0PWsbQLfhg",
        name : "Dumbbell One Arm Kickback",
        category : 'Tricep',
        //time : ,
    description : "This exercise helps to sculpt and tone your arms, increases your physical strength and also helps to trim body fat.",
},
{
    id : 36,
    image : "https://i.pinimg.com/236x/84/1e/6f/841e6f1024abc69e210707605c99a84c.jpg",
    youtube:"https://www.youtube.com/shorts/XQK1DB5CCZs",
    name : "Diamond Push-Ups",
    category : 'Tricep',
    //time : ,
    description : "Diamond push-ups are a variation of the classic push-up that target the triceps and other muscles in the upper body.",
},

//Shoulder Exercise.
{
    id : 37,
    image : "https://i.pinimg.com/originals/af/21/e5/af21e50b233235089a320388b246b1c0.jpg",
    youtube:"https://www.youtube.com/shorts/MRAZrd-eNEA",
    name : "Seated Arnold Press",
    category : 'Shoulder',
    //time : ,
    description : "The seated Arnold press can help you build strength in your shoulders and improve your stability.",
},
{
    id : 38,
    image : "https://i.pinimg.com/originals/57/07/83/57078380a7c0aa8c8d2cad12311fdbff.png",
    youtube:"https://www.youtube.com/shorts/DX5KA_cnH6Q",
    name : "Standing Front Rasie",
    category : 'Shoulder',
    //time : ,
    description : "Standing front raises mainly help strengthen and tone the front part of your shoulders (deltoids). They also improve shoulder stability and posture.",
},
{
    id : 39,
    image : "https://i.pinimg.com/originals/76/6b/99/766b99ec5af5b8e709b86deae085516a.jpg",
    youtube:"https://www.youtube.com/watch?v=mr2Ep0sSCIY",
    name : "Standing Lateral Rasie",
    category : 'Shoulder',
    //time : ,
    description : "Standing lateral raises mainly target and strengthen the side of your shoulders. They help build broader shoulders and improve overall shoulder strength and stability.",

},
{
    id : 40,
    image : "https://i.pinimg.com/originals/6c/0f/cb/6c0fcb0e08706e11de6069b729db4de7.png",
    youtube:"https://www.youtube.com/shorts/qmVoHKk4TKc",
    name : "Cable Front Raise",
    category : 'Shoulder',
    //time : ,
    description : "Cable front raises strengthen the front of your shoulders with constant tension from the cable. They help improve shoulder stability and muscle definition.",
},
{
    id : 41,
    image : "https://i.pinimg.com/originals/fe/cc/b1/feccb1f880a5f86763c98c68db06d758.jpg",
    youtube:"https://www.youtube.com/shorts/Xt14lA8V_ec",
    name : "Bar Upright Row",
    category : 'Shoulder',
    //time : ,
    description : "Barbell upright rows mainly work the shoulders and upper back, helping to build strength and definition. They also improve overall upper body stability and posture.",
},
{
    id : 42,
    image : "https://i.pinimg.com/originals/94/8c/1c/948c1c4ea0b39eb2a27b2d2621a91b54.jpg",
    youtube:"https://www.youtube.com/shorts/U8Y4pXZk9o4",
    name : "Cable Reverse Fly",
    category : 'Shoulder',
    //time : ,
    description : "It can help you improve your posture and balance your shoulder development.",

},
{
    id : 43,
    image : "https://i.pinimg.com/originals/3e/e4/14/3ee41417bfd0e4bf2510d7a2add170d5.jpg",
    youtube:"https://www.youtube.com/shorts/h_7ozLhN_wI",
    name : "Dumbell Shrugs last",
    category : 'Shoulder',
    //time : ,
    description : "Dumbbell shrugs strengthen the upper traps (trapezius muscles) in your shoulders. They help improve shoulder stability and posture by targeting the muscles that lift and support your shoulder blades.",
},

//Legs Exercise.
{
    id : 44,
    image : "https://i.pinimg.com/originals/c9/02/74/c90274de4687a534bee8ba0b0cc2daf7.jpg",
    youtube:"https://www.youtube.com/shorts/b-CqXqSIYm0",
    name : "Squats",
    category : 'Legs',
    //time : ,
    description : "Squats strengthen your glutes, hamstrings, quadriceps, and calves. They also help build muscle mass.",
},
{
    id : 45,
    image : "https://i.pinimg.com/originals/8f/8c/a2/8f8ca24215b5445acd0e321f2c380352.jpg",
    youtube:"https://www.youtube.com/shorts/s70RZRiuRyg",
    name : "Barbell Squal",
    category : 'Legs',
    //time : ,
    description : "This ultimate leg workout combines compound moves with resistance exercises to give you strong, muscular legs.",

},
{
    id : 46,
    image : "https://i.pinimg.com/originals/6c/52/8b/6c528b2222d92f0b48bbeca9a2dda84b.jpg",
    youtube:"https://www.youtube.com/shorts/G6AWv6DplnU",
    name : "Barbell Romain Deadlift",
    category : 'Legs',
    //time : ,
    description : "Add these lower back exercises to your regular gym routine to build strength, improve mobility, increase performance, and reduce pain.",
},
{
    id : 47,
    image : "https://i.pinimg.com/originals/41/e6/69/41e66934b48db6fc80baa424fc9e4795.jpg",
    youtube:"https://www.youtube.com/shorts/3jdtsvYzM3k",
    name : "Barbell Hip Thrust",
    category : 'Legs',
    //time : ,
    description : "Leg day Pirmdiena lower body Otrdiena upper body Trešdiena rest Ceturdiena lower body Piektdiena upper body Sestdiena rest Svetdiena rest Lower body Leg extentions",
},
{
    id : 48,
    image : "https://i.pinimg.com/1200x/ab/10/f7/ab10f73235d3fd3ed522602edbc4dc6e.jpg",
    youtube:"https://www.youtube.com/shorts/-DJIX0jfvYA",
    name : "Leg Lunges",
    category : 'Legs',
    //time : ,
    description : "Diese Moves verbrennen ratzfatz 100 Kalorien in weniger als einer Viertelstunde",

},
{
    id : 49,
    image : "https://i.pinimg.com/originals/6e/77/3d/6e773d8f6913a93bf2a3e3d31e1e3f0f.gif",
    youtube:"https://i.pinimg.com/originals/6e/77/3d/6e773d8f6913a93bf2a3e3d31e1e3f0f.gif",
    name : "Legs Machine Press",
    category : 'Legs',
    //time : ,
    description : "De leg press is een populaire oefening voor het trainen van de grote bilspieren en de bovenbenen . Bekijk hier hoe deze oefening werkt.",
},
{
    id : 50,
    image : "https://i.pinimg.com/originals/96/e6/a0/96e6a06d48a8531912fa2e0a278b13a1.jpg",
    youtube:"https://www.youtube.com/shorts/hnLIZ5LK0y8",
    name : "Leg Extension",
    category : 'Legs',
    //time : ,
    description : "Leg extension exercises are commonly used to target the quadriceps muscles of the thigh. However, there are alternative exercises that can be just as",
},
{
    id : 51,
    image : "https://i.pinimg.com/originals/56/59/d8/5659d804f3b1bb2c315e99bb416eb9cd.jpg",
    youtube:"https://www.youtube.com/shorts/vbkbYSBKebc",
    name : "Leg Curl",
    category : 'Legs',
    //time : ,
    description : "The hamstring curl, also called a leg curl, is an exercise that strengthens the hamstrings.",

},
{
    id : 52,
    image : "https://i.pinimg.com/474x/7b/9b/26/7b9b267719e0b7ed0881d93060c2dcd3.jpg",
    youtube:"https://www.youtube.com/shorts/qIVDOtRuzNA",
    name : "Standing Calf Raises",
    category : 'Legs',
    //time : ,
    description : "The world of fitness is filled with a myriad of exercises, each targeting specific muscle groups and offering unique benefits.",
},
]
export default ClassMenu;